version: '3'

services:
    web:
        container_name: web
        build: ./docker/php
        ports:
            - "${WEB_PORT}:80"
        depends_on:
            - db
        volumes:
           - ./www:/var/www

    db:
        container_name: db
        image: mysql:5.7
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: boilerplate
            MYSQL_USER: boilerplate
            MYSQL_PASSWORD: boilerplate
            MYSQL_ROOT_PASSWORD: root
